### ISSUE TITLE
[Bug] Program crash if you save health twice

### ISSUE THREAD

**Issue by kernelENREK** [siegrest/LogOut#1]
![image](https://user-images.githubusercontent.com/4211853/36045920-8ee8123e-0dd7-11e8-9aa1-48a1bb4e3b62.png)

It's easy to fix

**Comment by siegrest** [comment]
Fixed, hopefully [here](https://github.com/siegrest/LogOut/commit/0e1d4d647ac7adb2a23eb2d08a704980dbbb5fee)
