### ISSUE TITLE
[enhancement] Show a 'big' health bar overlaying the game

### ISSUE THREAD

**Issue by kernelENREK** [siegrest/LogOut#2]
I implemented a similar _tool_ a week after league start, 2 months ago (no public released). Also tracks HP globe but i'm using a more accurate algorithm:

![image](https://user-images.githubusercontent.com/4211853/36046225-7caf3f10-0dd8-11e8-8eec-818c37135955.png)

Think it should be a nice enhancement for your tool implementing somethink like i did.

**Comment by nibbydev** [comment]
Very nice idea. Added to todo list.
