### ISSUE TITLE
Getting invalid offset: -1 

### ISSUE THREAD

**Issue by MrMangolo** [siegrest/LogOut#6]
Hey,

im getting the error mentioned. You know why?
Im playing on 1920x1080 dx11 borderless.
Your old version where you tracked the healthglobe worked fine.
Just saw you pushed a new release, which i havent tried yet.
Going to try it later. 

Sincerely,
Mango

**Comment by nibbydev** [comment]
Offset -1 means it couldn't find the health bar above your character's head. Most of the time this can be ignored. I'd recommend grabbing the latest pre-release from [here](https://github.com/siegrest/LogOut/releases).  Unfortunately, that version doesn't have the offset -1 error anymore (so it's hard to tell if it's fixed). Try enabling "Show capture area" and if it looks like this then it should be fine:
![Tracker](http://gc-p.co/c/2b9bea87.png)

**Comment by nibbydev** [comment]
Closed due to inactivity
